export const SPECIALTIES = [
  { name: "Small Animal Medicine", icon: "🐕" },
  { name: "Veterinary Surgery", icon: "🔬" },
  { name: "Veterinary Cardiology", icon: "❤️" },
  { name: "Exotic Pet Medicine", icon: "🦜" },
  { name: "Veterinary Dermatology", icon: "✨" },
  { name: "Emergency & Critical Care", icon: "🚨" },
  { name: "Veterinary Dentistry", icon: "🦷" },
  { name: "Veterinary Ophthalmology", icon: "👁️" },
  { name: "Veterinary Neurology", icon: "🧠" },
  { name: "Veterinary Oncology", icon: "🎗️" },
  { name: "Internal Medicine", icon: "⚕️" },
  { name: "Behavioral Medicine", icon: "🐾" },
  { name: "Orthopedic Surgery", icon: "🦴" },
  { name: "General Practice", icon: "🏥" },
  { name: "Emergency Medicine", icon: "🚑" },
];